# Site settings
title: "Dr. Fan's Homepage"
description: "Dr. Fan's Homepage"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Miao Fan"
resume_title:                   "Profile"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "miao.fan@ieee.org"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "(+86)13581700448"
# resume_contact_address:         "Beijing, P.R.China"

resume_header_contact_info:     "https://scholar.google.com/citations?user=aPlHReAAAAAJ"
display_header_contact_info:    "true"

resume_header_intro: "
<p>Chief scientist and Head of AI at Navinfo Co., Ltd</p>

<p>Adjunct associate professor at Renmin University of China</p>

<p>IEEE Senior Member</p>

<p>Author of books \"Machine Learning with Python for Kaggle Competitions\" and \"AI Programming with Python in Practice\"</p>

<p>20+ top-tier papers with 1400+ citations</p>

<p>50+ granted patents and 10+ software copyrights</p>
"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:          false
resume_section_associations:    true
resume_section_grants:          false
resume_section_monographs:        true
resume_section_articles:        false
resume_section_patents:        false
resume_section_softwares:        false
resume_section_media:        false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/godfanmiao/"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://scholar.google.com/citations?user=aPlHReAAAAAJ&hl=zh-CN"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
